- name: Instalando Apache
  apt:
    name: apache2
    update_cache: yes
    state: present
  
- name: Habilitando Dependencias do Apache
  command: "a2enmod {{ item }}"
  loop:
  - proxy
  - rewrite
  - proxy_ajp
  - proxy_http

- name: Reiniciando o Apache
  systemd: 
    name: apache2
    state: restarted     
