- include: apache_install.yml
- include: mysql_install.yml
- include: mysql_create_db.yml
- include: java_install.yml
- include: wecorp_install.yml
- include: etherpad.yml
  when: ansible_facts['distribution_major_version'] == "16" or ansible_facts['distribution_major_version'] == "18" or ansible_facts['os_family'] == "RedHat"
- include: configure_backup.yml
