- name: Copiando aplicação Wecorp
  copy:
    src: "{{ dbname }}.tar.{{ file }}"
    dest: "/tmp/"

- name: Descompacta a aplicação
  unarchive: 
    src: "/tmp/{{ dbname }}.tar.{{ file }}"
    dest: /servicios
    remote_src: yes

- name: Copiando arquivos portal-setup-wizard.properties
  template:
    src: portal-setup-wizard.properties.j2
    dest: "/servicios/{{ dbname }}/portal-setup-wizard.properties"  

- name: Copiando server.xml 
  template:
    src: server.xml.j2
    dest: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/conf/server.xml"
  
- name: Copiando arquivo portal-ext.properties
  template:
    src: portal-ext.properties.j2
    dest: "/servicios/{{ dbname }}/portal-ext.properties"

- name: Copiando arquivo catalina.sh
  copy:
    src: catalina.sh
    dest: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/bin"

- name: Copiando arquivo setenv.sh
  copy:
    src: setenv.sh
    dest: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/bin"

- name: Criando diretorio logs
  file:
    path: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/logs"
    owner: root
    group: root
    mode: '0775'
    state: directory

- name: Copiando arquivo catalina.out
  copy:
    src: catalina.out
    dest: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/logs"

- name: Aplicando permissoes catalina.out
  file:
    path: "/servicios/{{ dbname }}/tomcat-{{ tomcat }}/logs/catalina.out"
    owner: root
    group: root
    mode: '0775'
    state: file

- name: Limpando diretorio /TMP
  command: rm -rf /tmp/*
