- name: Criando Diretorio de Backup
  file:
    path: "/home/bi/{{ env }}/bkp_{{ansible_date_time.date}}"
    owner: root
    group: root
    mode: '0775'
    state: directory
  tags:
  - backup

- name: Realizando Backup da Aplicacao
  archive:
    path: "{{ document_root }}"
    dest: "/home/bi/{{ env }}/bkp_{{ansible_date_time.date}}/{{ env }}_{{ansible_date_time.date}}.tar.bz2"
    format: bz2
  tags:
  - backup

- name: Realizando Backup do Bando de Dados
  mysql_db:
    name: "{{ database }}"
    state: dump
    target: "/home/bi/{{ env }}/bkp_{{ansible_date_time.date}}/{{ env }}_{{ansible_date_time.date}}.sql"
    login_user: "root"
    login_password: "Tlsbr8104"
  tags:
  - backup
