- name: Setting Fact Regionais
  set_fact:
    document_root: "/var/www/html/dceq/regionais"
    database: "rel-regionais"
  when: 
  - env == "regionais"
  tags:
  - setfact

- name: Setting Fact Scrum
  set_fact:
    document_root: "/var/www/html/dceq/scrum"
    database: "dceq-scrum"
  when:
  - env == "scrum"
  tags:
  - setfact
      
