---
- name: Playbook Iron Man
  hosts: "{{ inventario }}"
  vars:
    - username: tony
  tasks:
  - name: Comando de teste
    command: uptime
    register: resultado

  - name: Visualizando o resultado
    debug:
      var: resultado.stdout
      #msg: mensagem 

  - name: Instalando Pacotes Aleatorios - Like Ubuntu
    apt:
      name: ['sl','cowsay']
      update_cache: yes
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Instalando Pacotes Aleatorios - Like RedHat
    yum:
      name: "{{ item }}"
      state: present
    when: ansible_distribution == "RedHat"
    loop:
      - epel-release
      - ['sl','cowsay']

  - name: Ajustando PATH
    lineinfile:
      path: /etc/profile
      line: "export PATH=$PATH:/usr/games"
      state: present   

  - name: Garantindo Dominios
    blockinfile:
      path: /etc/hosts
      state: present
      block: |
        192.168.99.10 devops.com.br devops
        192.168.99.20 docker.com.br docker
        192.168.99.30 automation.com.br automation   
  
  - name: Criando usuario
    user: name={{ username }} shell=/bin/bash create_home=yes

  - name: Copiando arquivos
    copy:
      src: /etc/passwd
      dest: "/home/{{ username }}"

  - name: Instalando NGINX
    package:
      name: nginx
      state: present
    when: ansible_distribution == "Ubuntu"
    notify: reiniciar    

  handlers:
  - name: reiniciar
    systemd:
      name: nginx
      state: restarted
