version: '3'
services:
 
  #ZABBIX PROXY
  zabbix-proxy:
    depends_on:
      - mysql-zabbix-proxy
    image: zabbix/zabbix-proxy-mysql:centos-4.0-latest
    volumes:
      - zabbix_usr_lib_proxy:/usr/lib/zabbix
      - zabbix_var_lib_proxy:/var/lib/zabbix
      - zabbix_etc_proxy:/etc/zabbix
      - zabbix_var_log_proxy:/var/log/zabbix
    environment:
      DB_SERVER_HOST: mysql-zabbix-proxy
      MYSQL_USER: <user>
      MYSQL_PASSWORD: <password>
      ZBX_SERVER_HOST: <zabbixserverip>
      ZBX_PROXYMODE: 0
      ZBX_HOSTNAME: proxy-ted
      ZBX_SERVER_PORT: 10052
    ports:
      - 10051:10051
    networks:
      - zabbix-proxy_net
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '2'
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 10s

  #ZABBIX MYSQL PROXY
  mysql-zabbix-proxy:
    image: mysql:5.7
    volumes:
      - db_data_proxy:/var/lib/mysql
      - db_conf_proxy:/etc/mysql
      - db_logs_proxy:/var/log/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      MYSQL_ROOT_PASSWORD: <password>
    networks:
      - zabbix-proxy_net
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: '2'
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any

networks:
  zabbix-proxy_net:
    
volumes:
  db_data_proxy: {}
  db_conf_proxy: {}
  db_logs_proxy: {}
  zabbix_usr_lib_proxy: {}
  zabbix_var_lib_proxy: {}
  zabbix_etc_proxy: {}
  zabbix_var_log_proxy: {}
