---
# tasks file for pymysql
- name: Install Python-PyMySQL
  apt:
    name: python-pymysql
    update_cache: yes
    state: present
  when: ansible_facts['distribution_major_version'] == "16" or ansible_facts['distribution_major_version'] == "18" or ansible_facts['os_family'] == "RedHat"

- name: Install Pip
  apt:
    name: python-pip
    update_cache: yes
    state: present
  when: ansible_facts['distribution_major_version'] == "14"

- pip:
    name: pymysql
  when: ansible_facts['distribution_major_version'] == "14"
