- name: Instalando Apache
  apt:
    name: apache2
    update_cache: yes
    state: present
  
- name: Habilitando Dependencias do Apache
  command: "a2enmod {{ item }}"
  loop:
  - proxy
  - rewrite
  - proxy_ajp
  - proxy_http

- name: Copiando Template Apache
  template: 
    src: dominio.conf
    dest: "/etc/apache2/sites-available/{{ dominio }}.conf"

- name: Ativando WebHost
  command: "a2ensite {{ dominio }}.conf"
  notify: apacherestart
