---
# tasks file for etherpad
- name: Instalando dependencias do etherpad
  apt:
    name: ['gzip','git','curl','python','libssl-dev']
    update_cache: yes
    state: present

- name: Instalando dependencias do etherpad 2 
  apt:
    name: ['pkg-config','gcc','g++','make','build-essential']
    update_cache: yes
    state: present

- name: Instalando nodejs
  shell: 'curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - && sudo apt-get install -y nodejs'

- name: Adicionando usuario Etherpad
  user: 
    name: 'etherpad'
    shell: '/bin/bash' 
    create_home: yes

#- name: Adicionando repositorio Etherpad
#  git:
#    repo: https://github.com/ether/etherpad-lite.git
#    dest: /home/etherpad/etherpad-lite

#- name: Executando Script Etherpad
#  shell: 'sh /home/etherpad/etherpad-lite/bin/run.sh --root'

- name: Copiando Etherpad
  copy: 
    src: etherpad-lite.tar.bz2
    dest: /tmp/etherpad-lite.tar.bz2

- name: Descompactando Etherpad
  unarchive:
    src: /tmp/etherpad-lite.tar.bz2
    dest: /home/etherpad
    remote_src: yes

- name: Alterando permissoes da pasta Etherpad
  file:
    path: /home/etherpad/etherpad-lite
    state: directory
    recurse: yes
    owner: etherpad
    group: etherpad
    mode: '0775'

- name: Copiando arquivo de servico do Etherpad
  copy:
    src: etherpad.service
    dest: /etc/systemd/system/etherpad.service

- name: Iniciando serviço etherpad e daemon-reload
  systemd:
    state: started
    daemon_reload: yes
    name: etherpad

