- name: Instalando MySQL
  apt: 
    name: ['mysql-client','mysql-server']
    update_cache: yes
    state: present

- name: Instalando Libreoffice
  apt:
    name: libreoffice
    update_cache: yes
    state: present
  
- name: Iniciando MySQL
  systemd:
    name: mysql
    state: started
  when: ansible_facts['distribution_major_version'] == "16" or ansible_facts['distribution_major_version'] == "18" or ansible_facts['os_family'] == "RedHat"

- name: Iniciando MySQL-14
  service:
    name: mysql
    state: started
  when: ansible_facts['distribution_major_version'] == "14"

- name: Editando arquivos mysqld.cnf
  blockinfile: 
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    state: present
    block: | 
      lower_case_table_names = 1
      character-set-server=utf8
      collation-server=utf8_general_ci
  when: ansible_facts['distribution_major_version'] == "16" or ansible_facts['distribution_major_version'] == "18" or ansible_facts['os_family'] == "RedHat"

- name: Editando arquivos mysqld.cnf-14
  blockinfile:
    path: /etc/mysql/my.cnf
    state: present
    block: |
      lower_case_table_names = 1
      character-set-server=utf8
      collation-server=utf8_general_ci
  when: ansible_facts['distribution_major_version'] == "14"

- name: Reinicia o MySQL
  systemd:
    name: mysql
    state: restarted
  when: ansible_facts['distribution_major_version'] == "16" or ansible_facts['distribution_major_version'] == "18" or ansible_facts['os_family'] == "RedHat"

- name: Reinicia o MySQL-14
  service:
    name: mysql
    state: restarted
  when: ansible_facts['distribution_major_version'] == "14"
  
