- name: Instalando MySQL
  apt: 
    name: ['mysql-client','mysql-server']
    update_cache: yes
    state: present

- name: Instalando Libreoffice
  apt:
    name: libreoffice
    update_cache: yes
    state: present
  
- name: Iniciando MySQL
  systemd:
    name: mysql
    state: started

- name: Editando arquivos mysqld.cnf
  blockinfile: 
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    state: present
    block: | 
      lower_case_table_names = 1
      character-set-server=utf8
      collation-server=utf8_general_ci

- name: Reinicia o MySQL
  systemd:
    name: mysql
    state: restarted
