- name: Copiando arquivo DUMP da aplicação BASE
  copy:
    src: "{{ dbname }}.sql"
    dest: /tmp

- name: Criando Base de Dados
  mysql_db:
    name: "{{ dbname }}"
    state: present
    encoding: utf8
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Atualizando user root
  mysql_user:
    host: "localhost"
    check_implicit_admin: yes
    name: root
    password: Mudar123@
    priv: "*.*:ALL,GRANT"
    state: present
    login_unix_socket: "/var/run/mysqld/mysqld.sock"

- name: Criando Usuario MySQL para aplicação
  mysql_user:
    login_user: "root"
    login_password: "Mudar123@"
    host: 'localhost'
    name: appwecorp
    password: 'Wecorp99@'
    priv: '{{ dbname }}.*:ALL,GRANT'
    state: present

- name: Criando Usuario MySQL para dev
  mysql_user:
    login_user: "root"
    login_password: "Mudar123@"
    host: '%'
    name: devlogs
    password: 'Ted10gs'
    priv: '{{ dbname }}.*:{{ item.permission }},GRANT'
    state: present
  when: "'{{ item.group }}' in group_names"
  loop:
  - { permission: "ALL", group: "dev" }
  - { permission: "SELECT", group: "cert" }

- name: Importar arquivo SQL para o banco criado
  mysql_db:
    login_user: "root"
    login_password: "Mudar123@"
    name: "{{ dbname }}"
    state: import
    target: "/tmp/{{ dbname }}.sql"
