- name: Baixar Pacote Puppet - RedHat
  get_url: 
    url: "https://yum.puppet.com/puppet6-release-el-7.noarch.rpm"
    dest: /tmp/
  when: ansible_os_family == 'RedHat'
  
- name: Baixar Pacote Puppet - Debian
  get_url: 
    url: "https://apt.puppet.com/puppet6-release-{{ansible_lsb.codename}}.deb"
    dest: /tmp/
  when: ansible_os_family == 'Debian'

