- name: Baixar Pacote Zabbix - RedHat
  get_url: 
    url: "https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm"
    dest: /tmp/repo.rpm
  when: ansible_os_family == 'RedHat'
  
- name: Baixar Pacote Zabbix - Ubuntu
  get_url: 
    url: "https://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-3+{{ansible_lsb.codename}}_all.deb"
    dest: /tmp/repo.deb
  when: ansible_os_family == 'Debian'

